# Generated by Django 5.0.6 on 2024-05-13 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='store.category', verbose_name='Основная категория'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_product', models.CharField(max_length=100, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('price_with_discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена со скидкой')),
                ('inventory_balance', models.PositiveSmallIntegerField(default=0, verbose_name='Товарный остаток')),
                ('product_characteristics', models.TextField(verbose_name='Характеристики товара')),
                ('category', models.ManyToManyField(related_name='category_product', to='store.category', verbose_name='Категория товара')),
                ('subcategory', models.ManyToManyField(related_name='subcategory_product', to='store.subcategories', verbose_name='Подкатегория товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
