# Generated by Django 5.0.6 on 2024-05-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcategories',
            new_name='Subcategory',
        ),
    ]
