# Generated by Django 5.0.6 on 2024-05-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_subcategories_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ManyToManyField(blank=True, null=True, related_name='subcategory_product', to='store.subcategory', verbose_name='Подкатегория товара'),
        ),
    ]
