# Generated by Django 5.0.6 on 2024-05-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ManyToManyField(related_name='subcategory_product', to='store.subcategory', verbose_name='Подкатегория товара'),
        ),
    ]
